/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etoko.view;

/**
 *
 * @author Arnold Vengeance
 */
public class BarangFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BarangFrame
     */
    public BarangFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barangPanel1 = new com.etoko.view.panel.BarangPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Master Barang");
        getContentPane().add(barangPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.etoko.view.panel.BarangPanel barangPanel1;
    // End of variables declaration//GEN-END:variables
}
