/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etoko.view;

/**
 *
 * @author Arnold Vengeance
 */
public class GudangFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form GudangFrame
     */
    public GudangFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gudangPanel1 = new com.etoko.view.panel.GudangPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Master Gudang");
        getContentPane().add(gudangPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.etoko.view.panel.GudangPanel gudangPanel1;
    // End of variables declaration//GEN-END:variables
}
