package com.etoko;

import com.etoko.dao.Barang_Dao;
import com.etoko.dao.Gudang_Dao;
import com.etoko.dao.Karyawan_Dao;
import com.etoko.dao.Kembali_Dao;
import com.etoko.dao.Transaksi_Dao;
import com.etoko.daointerface.Kembali_DaoInterface;
import com.etoko.laporan.dialog.TampilanLaporan;
import com.etoko.model.Barang;
import com.etoko.model.Gudang;
import com.etoko.model.Karyawan;
import com.etoko.model.Kembali;
import com.etoko.model.Laporan_Transaksi;
import com.etoko.view.BarangFrame;
import com.etoko.view.GudangFrame;
import com.etoko.view.InputBarangFrame;
import com.etoko.view.KaryawanFrame;
import com.etoko.view.KembaliFrame;
import com.etoko.view.TransaksiByTglFrame;
import com.etoko.view.TransaksiFrame;
import com.etoko.view.UpdateUserLogin;
import com.etoko.view.dialog.Login;
import com.etoko.view.dialog.Tentang;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Arnold Vengeance
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setLayar(JInternalFrame frame){
        DeskPanel.add(frame);
        Dimension layar=this.getSize();
        Dimension dim=frame.getSize();
        frame.setLocation((layar.width-dim.width)/2, (layar.height-dim.height)/2);
        frame.setVisible(true);
    }
    
    private void kasir(){
        MenuMaster.setVisible(false);
        menuLapKaryawan.setEnabled(false);
        menuInputBarang.setEnabled(false);
    }
    
    private void karyawan(){
        MenuMaster.setVisible(false);
        menuPenjualan.setEnabled(false);
        menuBarangKembali.setEnabled(false);
        menuLapKaryawan.setEnabled(false);
    }
    
    private void admin(){
        MenuMaster.setVisible(true);
        menuLapKaryawan.setEnabled(true);
        menuInputBarang.setEnabled(true);
        menuPenjualan.setEnabled(true);
        menuBarangKembali.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUbahUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuLogout = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();
        MenuMaster = new javax.swing.JMenu();
        menuGudang = new javax.swing.JMenuItem();
        menuKaryawan = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuInputBarang = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenuItem();
        menuBarangKembali = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        menuLapKaryawan = new javax.swing.JMenuItem();
        menuLapBarang = new javax.swing.JMenuItem();
        menuLapGudang = new javax.swing.JMenuItem();
        menuTransaksiByTanggal = new javax.swing.JMenuItem();
        menuLapSemuaTransaksi = new javax.swing.JMenuItem();
        menuLapReBarang = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Tentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout DeskPanelLayout = new javax.swing.GroupLayout(DeskPanel);
        DeskPanel.setLayout(DeskPanelLayout);
        DeskPanelLayout.setHorizontalGroup(
            DeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DeskPanelLayout.setVerticalGroup(
            DeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(DeskPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuUbahUser.setText("Ubah Data User");
        menuUbahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUbahUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuUbahUser);
        jMenu1.add(jSeparator1);

        menuLogout.setText("Logout User");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        MenuMaster.setText("Master");

        menuGudang.setText("Gudang");
        menuGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGudangActionPerformed(evt);
            }
        });
        MenuMaster.add(menuGudang);

        menuKaryawan.setText("Karyawan");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        MenuMaster.add(menuKaryawan);

        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        MenuMaster.add(menuBarang);

        jMenuBar1.add(MenuMaster);

        jMenu3.setText("Transaksi");

        menuInputBarang.setText("Input Barang");
        menuInputBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInputBarangActionPerformed(evt);
            }
        });
        jMenu3.add(menuInputBarang);

        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(menuPenjualan);

        menuBarangKembali.setText("Return Barang");
        menuBarangKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangKembaliActionPerformed(evt);
            }
        });
        jMenu3.add(menuBarangKembali);

        jMenuBar1.add(jMenu3);

        MenuLaporan.setText("Laporan");

        menuLapKaryawan.setText("Laporan Karyawan");
        menuLapKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapKaryawanActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuLapKaryawan);

        menuLapBarang.setText("Laporan Barang");
        menuLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapBarangActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuLapBarang);

        menuLapGudang.setText("Laporan Gudang");
        menuLapGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapGudangActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuLapGudang);

        menuTransaksiByTanggal.setText("Laporan Transaksi (Tanggal)");
        menuTransaksiByTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiByTanggalActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuTransaksiByTanggal);

        menuLapSemuaTransaksi.setText("Laporan Semua Transaksi");
        menuLapSemuaTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapSemuaTransaksiActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuLapSemuaTransaksi);

        menuLapReBarang.setText("Laporan Barang Kembali");
        menuLapReBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapReBarangActionPerformed(evt);
            }
        });
        MenuLaporan.add(menuLapReBarang);

        jMenuBar1.add(MenuLaporan);

        jMenu5.setText("Bantuan");

        Tentang.setText("Tentang");
        Tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TentangActionPerformed(evt);
            }
        });
        jMenu5.add(Tentang);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGudangActionPerformed
        GudangFrame frame=new GudangFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuGudangActionPerformed

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        KaryawanFrame frame=new KaryawanFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        BarangFrame frame=new BarangFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuInputBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInputBarangActionPerformed
        InputBarangFrame frame=new InputBarangFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuInputBarangActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        TransaksiFrame frame=new TransaksiFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuBarangKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangKembaliActionPerformed
        KembaliFrame frame=new KembaliFrame();
        setLayar(frame);
    }//GEN-LAST:event_menuBarangKembaliActionPerformed

    private void menuLapKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapKaryawanActionPerformed
        try {
            Karyawan_Dao dao=new Karyawan_Dao();
            List<Karyawan> karyawan = dao.getKaryawan();
            JasperPrint jPrint=JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/etoko/laporan/KaryawanLaporan.jasper"), 
                    null, new JRBeanCollectionDataSource(karyawan));
            JRViewer jv=new JRViewer(jPrint);
            TampilanLaporan laporan=new TampilanLaporan("Laporan Karyawan", jv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapKaryawanActionPerformed

    private void menuLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapBarangActionPerformed
        try {
            Barang_Dao dao=new Barang_Dao();
            List<Barang> barang = dao.getBarang();
            JasperPrint jPrint=JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/etoko/laporan/BarangLaporan.jasper"), 
                    null, new JRBeanCollectionDataSource(barang));
            JRViewer jv=new JRViewer(jPrint);
            TampilanLaporan laporan=new TampilanLaporan("Laporan Barang", jv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapBarangActionPerformed

    private void menuLapGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapGudangActionPerformed
        try {
            Gudang_Dao dao=new Gudang_Dao();
            List<Gudang> gudang = dao.getGudang();
            JasperPrint jPrint=JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/etoko/laporan/GudangLaporan.jasper"), 
                    null, new JRBeanCollectionDataSource(gudang));
            JRViewer jv=new JRViewer(jPrint);
            TampilanLaporan laporan=new TampilanLaporan("Laporan Gudang", jv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapGudangActionPerformed

    private void menuLapSemuaTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapSemuaTransaksiActionPerformed
        try {
            Transaksi_Dao dao=new Transaksi_Dao();
            List<Laporan_Transaksi> transaksi = dao.getTransaksi();
            HashMap map=new HashMap();
            map.put("subJudul", "Semua Transaksi");
            JasperPrint jPrint=JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/etoko/laporan/TransaksiLaporan.jasper"), 
                    map, new JRBeanCollectionDataSource(transaksi));
            JRViewer jv=new JRViewer(jPrint);
            TampilanLaporan laporan=new TampilanLaporan("Laporan Transaksi", jv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapSemuaTransaksiActionPerformed

    private void menuTransaksiByTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiByTanggalActionPerformed
        TransaksiByTglFrame transaksiTgl=new TransaksiByTglFrame();
        setLayar(transaksiTgl);
    }//GEN-LAST:event_menuTransaksiByTanggalActionPerformed

    private void menuLapReBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapReBarangActionPerformed
        try {
            Kembali_DaoInterface dao=new Kembali_Dao();
            List<Kembali> kembali = dao.getKembali();
            JasperPrint jPrint=JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream
                ("com/etoko/laporan/BarangRtnLaporan.jasper"), 
                    null, new JRBeanCollectionDataSource(kembali));
            JRViewer jv=new JRViewer(jPrint);
            TampilanLaporan laporan=new TampilanLaporan("Laporan Return Barang", jv);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapReBarangActionPerformed

    private void TentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TentangActionPerformed
        Tentang tentang=new Tentang();
        tentang.setTitle("About");
        tentang.setLocationRelativeTo(getParent());
        tentang.setVisible(true);
    }//GEN-LAST:event_TentangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Login login=new Login();
        Karyawan loginUser = login.loginUser();
        if(loginUser!=null){
            this.setTitle("E-Toko | "+loginUser.getNama()+" ["+loginUser.getStatus()+"]");
            switch (loginUser.getStatus()) {
                case "Admin":
                    admin();
                    break;
                case "Kasir":
                    kasir();
                    break;
                case "Karyawan":
                    karyawan();
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        Login login=new Login();
        Karyawan loginUser = login.loginUser();
        if(loginUser!=null){
            this.setTitle("E-Toko | "+loginUser.getNama()+" ["+loginUser.getStatus()+"]");
            switch (loginUser.getStatus()) {
                case "Admin":
                    admin();
                    break;
                case "Kasir":
                    kasir();
                    break;
                case "Karyawan":
                    karyawan();
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuUbahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUbahUserActionPerformed
        UpdateUserLogin ubahUser=new UpdateUserLogin();
        setLayar(ubahUser);
    }//GEN-LAST:event_menuUbahUserActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskPanel;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenu MenuMaster;
    private javax.swing.JMenuItem Tentang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuBarangKembali;
    private javax.swing.JMenuItem menuGudang;
    private javax.swing.JMenuItem menuInputBarang;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLapBarang;
    private javax.swing.JMenuItem menuLapGudang;
    private javax.swing.JMenuItem menuLapKaryawan;
    private javax.swing.JMenuItem menuLapReBarang;
    private javax.swing.JMenuItem menuLapSemuaTransaksi;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuTransaksiByTanggal;
    private javax.swing.JMenuItem menuUbahUser;
    // End of variables declaration//GEN-END:variables
}
