/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etoko.view.panel;

import com.etoko.dao.Gudang_Dao;
import com.etoko.daointerface.Gudang_DaoInterface;
import com.etoko.model.Gudang;
import com.etoko.tabelModel.TabelModel_Gudang;
import com.etoko.view.dialog.GudangDialog;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Arnold Vengeance
 */
public class GudangPanel extends javax.swing.JPanel {

    private TabelModel_Gudang tabelModelGudang=new TabelModel_Gudang();
    private Gudang_DaoInterface gudangDaoIF=new Gudang_Dao();
    
    public GudangPanel() {
        initComponents();
        tblGudang.setModel(tabelModelGudang);
        muatData();
    }
    
    private void muatData(){
        List<Gudang> gudang = gudangDaoIF.getGudang();
        tabelModelGudang.setData(gudang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGudang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jScrollPane1.setViewportView(tblGudang);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        GudangDialog dialog=new GudangDialog();
        Gudang insertGudang = dialog.insertGudang();
        if(insertGudang!=null){
            gudangDaoIF.insert(insertGudang);
            muatData();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if(tblGudang.getSelectedRow()!=-1){
            int index=tblGudang.getSelectedRow();
            Gudang gudang = tabelModelGudang.getGudang(tblGudang.convertRowIndexToModel(index));
            GudangDialog dialog=new GudangDialog();
            Gudang updateGudang = dialog.updateGudang(gudang);
            if(updateGudang!=null){
                gudangDaoIF.update(updateGudang);
                tabelModelGudang.updateGudang(index, gudang);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih data Gudang!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int index=tblGudang.getSelectedRow();
        if(index!=-1){
            Gudang gudang = tabelModelGudang.getGudang(tblGudang.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin?", "Konfirmasi Hapus",
                    JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                gudangDaoIF.delete(gudang);
                tabelModelGudang.deleteGudang(index);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleksi salah satu Gudang!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        muatData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGudang;
    // End of variables declaration//GEN-END:variables
}
